In [1]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

In [2]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 [==============================] - 4s 0us/step


In [3]:
x_train=x_train.reshape((x_train.shape[0]),x_train.shape[1],x_train.shape[2],1)
x_test=x_test.reshape((x_test.shape[0]),x_test.shape[1],x_test.shape[2],1)

In [4]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [5]:
x_train=x_train/255
x_test=x_test/255

In [6]:
print(x_train)
print(x_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [7]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [13]:
model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(MaxPool2D(2,2)) 
model.add(Flatten())
model.add(Dense(100,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [14]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 46s 24ms/step - loss: 0.1598 - accuracy: 0.9532
Epoch 2/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0519 - accuracy: 0.9842
Epoch 3/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0340 - accuracy: 0.9897
Epoch 4/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0229 - accuracy: 0.9930
Epoch 5/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0178 - accuracy: 0.9944
Epoch 6/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0110 - accuracy: 0.9967
Epoch 7/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0088 - accuracy: 0.9973
Epoch 8/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0070 - accuracy: 0.9978
Epoch 9/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0061 - accuracy: 0.9980
Epoch 10/10
1875/1875 [==============================] - 45s 24m

In [17]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 3s 9ms/step - loss: 0.0623 - accuracy: 0.9854


[0.06234534829854965, 0.9854000210762024]